[package]
name = "people-lib"
version = "0.1.0"
authors = ["Tim <timothyhollabaugh@gmail.com>", "Lizzie <amorye7@students.rowan.edu>"]

[dependencies]
database-lib = { git = "https://github.com/Rowan-ECE-Resource-Center/database_lib"}